### ISSUE TITLE
Play random from a whole category doesn't work

### ISSUE THREAD

**Issue by amritpal7205** [lindell/home-assistant-svt-play#19]
Playing a ranom episode from a given 'program_name. works perfect!
service: svt_play.play_random
data:
  entity_id: media_player.chromecastultra7388
  program_name: svenska-nyheter
  
However, playing a random episode of some program within a whole category doesn't work. 
service: svt_play.play_random
data:
  entity_id: media_player.chromecastultra7388
  category: humor

In fact the service fails as soon as the 'category' is added to the data:
service: svt_play.play_random
data:
  entity_id: media_player.chromecastultra7388
  program_name: svenska-nyheter
  category: humor

**Comment by lindell** [comment]
What does the log say when it errors?

**Comment by fldc** [comment]
Är tanken att detta ska fungera? Jag försökte skapa ett skript som spelar random från barn.

Detta är felmeddelande ur logg.

2023-08-13 18:42:22.125 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/svt_play/__init__.py", line 113, in play_random
    video_info = await hass.async_add_executor_job(fetch_video_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/svt_play/__init__.py", line 111, in fetch_video_url
    random_video_id(program_name, categories=category)
  File "/config/custom_components/svt_play/video_url_fetch/video_fetch.py", line 84, in random_video_id
    program_data = information_by_program_id(program_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/svt_play/video_url_fetch/video_fetch.py", line 138, in information_by_program_id
    if len(data['data']['listablesBySlug']) < 1:
           ~~~~^^^^^^^^
KeyError: 'data'
