### ISSUE TITLE
Invalid media type: video

### ISSUE THREAD

**Issue by EagleStClair** [lindell/home-assistant-svt-play#27]
Is this component not working anymore? I installed from hacs but when trying to use the actions with Android TV Remote integration it just gives the below error stating "incorrect media type: video"

I've tried play channel, play suggested and play latest but all services produces error.

```
Logger: homeassistant.core
Source: core.py:2781
First occurred: 11:56:00 (4 occurrences)
Last logged: 13:05:12

Error executing service: <ServiceCall media_player.play_media (c:01J87DR8QY05VPSM3HR68HY4R2): entity_id=['media_player.koket_android_tv_2'], extra=title=Sportnytt - Idag 09:41, thumb=https://www.svtstatic.se/image/large/1024/51952563/1726819542?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-8j.akamaized.net/d0/se/20240920/943b6508-bd08-41d1-a57e-b045cbddd024/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01J87HJV91STPAZZGSNJNNKY54): entity_id=['media_player.koket_android_tv_2'], extra=title=Sportnytt - Idag 09:41, thumb=https://www.svtstatic.se/image/large/1024/51952563/1726819542?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-8j.akamaized.net/d0/se/20240920/943b6508-bd08-41d1-a57e-b045cbddd024/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01J87HN0MRVXH50MNQYKHA5YJA): entity_id=['media_player.koket_android_tv_2'], extra=, media_type=video, media_id=https://svt-live-channel.akamaized.net/l0/se/svt1/master.m3u8?defaultSubLang=1>
Error executing service: <ServiceCall media_player.play_media (c:01J87HPZ6DD67RY7VW3FFQDSE5): entity_id=['media_player.koket_android_tv_2'], extra=title=Sportnytt - Idag 09:41, thumb=https://www.svtstatic.se/image/large/1024/51952563/1726819542?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-8j.akamaized.net/d0/se/20240920/943b6508-bd08-41d1-a57e-b045cbddd024/hls-ts-avc.m3u8>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2781, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/androidtv_remote/media_player.py", line 191, in async_play_media
    raise ValueError(f"Invalid media type: {media_type}")
ValueError: Invalid media type: video
```

**Comment by EagleStClair** [comment]
Never mind, need to use the media_player from cast integration, not Android TV remote (that one only accepts app, url and channel.)
